In [86]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
svm= SVC()

In [87]:
df = pd.read_csv('realolignal_test12.csv')

In [97]:
df.to_csv('realolignal_test12전처리.csv',index_label=False)

,wd_plnt_nm,wd_plnt_idntfr,object_class_lclas_code,object_class_mlsft_code,object_class_sclas_code,woody_herbal,region_nm_농산물원종장,region_nm_동광리,region_nm_만장굴,region_nm_무수천,...,irdnt_ncl_0.2|-0.4|0.0|0.1|0.6|0.6|0.7|0.3|0.4|0.6,irdnt_ncl_0.2|1.0|0.2|-0.5|-0.3|0.1|0.9|0.2|0.0|0.2,irdnt_ncl_0.4|0.9|0.3|0.2|0.9|0.1|0.6|0.0|-0.6|0.4,irdnt_ncl_0.5|0.3|0.8|1.3|0.6|0.4|1.6|0.7|1.7|3.5,irdnt_ncl_0.5|0.7|0.0|-0.6|-0.1|0.3|0.8|0.4|0.3|0.0,irdnt_ncl_0.6|0.4|-0.3|0.5|-0.4|0.0|0.0|-0.2|0.4|0.5,irdnt_ncl_2.8|0.4|0.4|-0.3|0.2|0.0|0.6|0.0|0.2|0.6,irdnt_ncl_분석 진행중,irdnt_chmcls_strct_,irdnt_anals_instlm_제주산학융합원
0,4,9,2,9,2,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
1,4,9,2,9,2,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
2,4,9,2,9,2,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
3,4,9,2,9,2,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
4,4,9,2,9,2,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,4,9,2,9,5,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
10123,4,9,2,9,5,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
10124,4,9,2,9,5,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
10125,4,9,2,9,5,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
10126,4,9,2,9,5,2,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1

In [88]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'wd_plnt_nm', 'wd_plnt_idntfr',
       'region_nm', 'region_type', 'plant_part', 'grwh_step_nm',
       'image_file_frmat', 'image_potogrf_dt', 'antn_ty',
       'object_class_lclas_code', 'object_class_mlsft_code',
       'object_class_sclas_code', 'object_class_lclas_nm',
       'object_class_sclas_nm', 'pyn_xcrdnt', 'pyn_ycrdnt', 'scientific_nm',
       'woody_herbal', 'edible_yn', 'edible_part', 'acquisition_term',
       'efficacy', 'efficacy_ncl', 'irdnt_nm', 'irdnt_ncl',
       'irdnt_chmcls_strct', 'irdnt_anals_instlm'],
      dtype='object')

In [ ]:
# del df['object_class_mlsft_nm']

In [ ]:
df.object_class_mlsft_nm

In [ ]:
df.columns

In [91]:
df['wd_plnt_nm']=le.fit_transform(df['wd_plnt_nm'])

In [93]:
df = pd.get_dummies(df)
df

,Unnamed: 0,Unnamed: 0.1,wd_plnt_nm,wd_plnt_idntfr,object_class_lclas_code,object_class_mlsft_code,object_class_sclas_code,woody_herbal,region_nm_농산물원종장,region_nm_동광리,...,irdnt_ncl_0.2|-0.4|0.0|0.1|0.6|0.6|0.7|0.3|0.4|0.6,irdnt_ncl_0.2|1.0|0.2|-0.5|-0.3|0.1|0.9|0.2|0.0|0.2,irdnt_ncl_0.4|0.9|0.3|0.2|0.9|0.1|0.6|0.0|-0.6|0.4,irdnt_ncl_0.5|0.3|0.8|1.3|0.6|0.4|1.6|0.7|1.7|3.5,irdnt_ncl_0.5|0.7|0.0|-0.6|-0.1|0.3|0.8|0.4|0.3|0.0,irdnt_ncl_0.6|0.4|-0.3|0.5|-0.4|0.0|0.0|-0.2|0.4|0.5,irdnt_ncl_2.8|0.4|0.4|-0.3|0.2|0.0|0.6|0.0|0.2|0.6,irdnt_ncl_분석 진행중,irdnt_chmcls_strct_,irdnt_anals_instlm_제주산학융합원
0,0,0,4,9,2,9,2,2,0,0,...,0,0,0,0,0,1,0,0,1,1
1,1,1,4,9,2,9,2,2,0,0,...,0,0,0,0,0,1,0,0,1,1
2,2,2,4,9,2,9,2,2,0,0,...,0,0,0,0,0,1,0,0,1,1
3,3,3,4,9,2,9,2,2,0,0,...,0,0,0,0,0,1,0,0,1,1
4,4,4,4,9,2,9,2,2,0,0,...,0,0,0,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,10122,10122,4,9,2,9,5,2,0,0,...,0,0,0,0,0,1,0,0,1,1
10123,10123,10123,4,9,2,9,5,2,0,0,...,0,0,0,0,0,1,0,0,1,1
10124,10124,10124,4,9,2,9,5,2,0,0,...,0,0,0,0,0,1,0,0,1,1
10125,10125,10125,4,9,2,9,5,2,0,0,...,0,0,0,0,0,1,0,0,1,1
10126,10126,10126,4,9,2,9,5,2,0,0,...,0,0,0,0,0,1,0,0,1,1

In [98]:
X_train,X_test,y_train,y_test = train_test_split(
    df.iloc[:,1:],df['wd_plnt_nm'],stratify=df['wd_plnt_nm']
)

In [99]:
svm.fit(X_train,y_train)

SVC()

In [100]:
svm.score(X_test,y_test)

1.0

In [54]:
X_train.shape,y_train.shape

((7595, 27498), (7595,))

### 실패